/**
 * v3.13.0 — verification assessments client.
 *
 * Every call goes to supabase/functions/resume-hub with a session JWT.
 * Nothing here can reach a rubric, a score, or a verdict on the candidate
 * lane: those live in tables the anon and authenticated roles have no
 * privileges on at all, and no candidate action returns them.
 */
import { supabase } from "@/integrations/supabase/client";
import { SUPABASE_URL } from "@/config";
import { maintenanceErrorFrom } from "@/lib/featureError";

const FN = `${SUPABASE_URL}/functions/v1/resume-hub`;

// v3.313.0 — real, reported bug: a stale access token after the tab sat
// idle/backgrounded a while produces a genuine 401 here too, same as
// resumeHub.ts's own identical fix (see that file's own comment for the
// full root cause). This file has its own separate call(), so it needed
// the same fix on its own path rather than inheriting the other one.
async function isExpiredJwt(status: number, data: unknown): Promise<boolean> {
  if (status !== 401) return false;
  const coded = data as { code?: string; message?: string; error?: string };
  return coded?.code === "PGRST301" || /jwt|invalid session|invalid token/i.test(String(coded?.message || coded?.error || ""));
}

async function call<T>(body: unknown): Promise<T> {
  const { data } = await supabase.auth.getSession();
  const token = data.session?.access_token;
  if (!token) throw new Error("Not signed in");
  const headers = {
    Authorization: `Bearer ${token}`,
    apikey: import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string,
    "Content-Type": "application/json",
  };
  const r = await fetch(FN, { method: "POST", headers, body: JSON.stringify(body) });
  const text = await r.text();
  let parsed: unknown;
  try { parsed = JSON.parse(text); } catch { parsed = { error: text }; }

  if (!r.ok && await isExpiredJwt(r.status, parsed)) {
    const { data: refreshed, error: refreshErr } = await supabase.auth.refreshSession();
    if (!refreshErr && refreshed.session) {
      const retryHeaders = { ...headers, Authorization: `Bearer ${refreshed.session.access_token}` };
      const r2 = await fetch(FN, { method: "POST", headers: retryHeaders, body: JSON.stringify(body) });
      const text2 = await r2.text();
      let parsed2: unknown;
      try { parsed2 = JSON.parse(text2); } catch { parsed2 = { error: text2 }; }
      if (r2.ok) return parsed2 as T;
      const maintenance2 = maintenanceErrorFrom(parsed2);
      if (maintenance2) throw maintenance2;
      throw new Error((parsed2 as { error?: string })?.error || `Request failed (${r2.status})`);
    }
  }
  if (!r.ok) {
    const maintenance = maintenanceErrorFrom(parsed);
    if (maintenance) throw maintenance;
    throw new Error((parsed as { error?: string })?.error || `Request failed (${r.status})`);
  }
  return parsed as T;
}

/** What the candidate is allowed to see. There is no rubric field here. */
export type PubQuestion = {
  id: string;
  type: "mc" | "short";
  text: string;
  options?: string[];
};

export type AssessmentStatus = "sent" | "started" | "submitted" | "expired";

/** Employer view. `result` is null until the candidate submits. */
export type EmployerAssessment = {
  id: string;
  ref: string | null;
  search_id: string | null;
  job_title: string | null;
  first_name?: string | null;
  status: AssessmentStatus;
  question_count: number;
  time_limit_seconds: number;
  sent_at: string | null;
  started_at: string | null;
  submitted_at: string | null;
  expires_at: string | null;
  result: {
    overall_score: number;
    verification_verdict: "consistent" | "partly consistent" | "inconsistent";
    per_question: Array<{
      id: string; question: string; answer: string;
      seconds_spent: number; score: number; observed: string;
      /** v3.154.0 — a live follow-up, generated only after the candidate
       * answered the question before it. Could not have been prepared. */
      is_follow_up?: boolean;
    }>;
    strengths: string[];
    concerns: string[];
    employer_summary: string;
    /** v3.154.0 — advisory only: does the answer prose itself read like it
     * was generated by an AI rather than typed under time pressure. Never
     * a hard signal on its own; shown alongside, not instead of, the
     * content-based verdict above. */
    writing_signal: "human" | "ai_assisted" | "unclear";
    writing_signal_note: string;
  } | null;
};

/** Candidate view. No score, no verdict, no observation, by design. */
export type SeekerAssessment = {
  id: string;
  org_name: string;
  org_logo_url: string | null;
  job_title: string;
  status: AssessmentStatus;
  question_count: number;
  time_limit_seconds: number;
  sent_at: string | null;
  expires_at: string | null;
  started_at: string | null;
  submitted_at: string | null;
  deadline_at: string | null;
};

export type StartedAssessment = {
  id: string;
  org_name: string;
  job_title: string;
  questions: PubQuestion[];
  answers: Record<string, { answer?: string; ms?: number }>;
  deadline_at: string;
  seconds_left: number;
};

export const assessmentApi = {
  // Employer lane
  generate: (org_id: string, search_id: string, ref: string) =>
    call<{ assessment_id: string; job_title: string; questions: PubQuestion[] }>({
      action: "employer_assessment_generate", org_id, search_id, ref,
    }),
  send: (assessment_id: string, keep_ids: string[], time_limit_seconds: number, expires_days: number) =>
    call<{ ok: true }>({
      action: "employer_assessment_send", assessment_id, keep_ids, time_limit_seconds, expires_days,
    }),
  employerList: (search_id?: string) =>
    call<{ assessments: EmployerAssessment[] }>({ action: "employer_assessment_list", search_id }),

  // Candidate lane
  list: () => call<{ assessments: SeekerAssessment[] }>({ action: "assessment_list" }),
  start: (id: string) => call<StartedAssessment>({ action: "assessment_start", id }),
  // v3.154.0 — a short answer can come back with a live follow-up: one
  // more question, generated only after this answer existed, that digs
  // for a specific detail the candidate could not have prepared in
  // advance. null when the question was multiple choice or no follow-up
  // was generated.
  answer: (id: string, question_id: string, answer: string, ms: number) =>
    call<{ ok: true; follow_up: PubQuestion | null }>({ action: "assessment_answer", id, question_id, answer, ms }),
  submit: (id: string) => call<{ ok: true; org_name: string }>({ action: "assessment_submit", id }),
  /** The growth note only. Never the assessment content or how they scored. */
  growthNotes: () => call<{ notes: string[] }>({ action: "assessment_growth_notes" }),
};

/** One honest line the employer UI must always show. */
export const ASSESSMENT_LIMIT_NOTE =
  "This checks depth of experience. It cannot prove someone answered unaided.";
