const expected = [
    "access_grants", "admin_notification_config", "admin_notification_log", "agent_event_debounce", 
    "agent_telegram_bots", "ai_mode_configs", "alert_history", "api_rate_limits", "app_settings", 
    "application_replies", "ayn_accuracy_calibration", "ayn_activity_log", "ayn_agent_coalitions", 
    "ayn_agent_memory", "ayn_agent_memory_log", "ayn_agent_messages", "ayn_agent_opinion_shifts", 
    "ayn_agent_relationships", "ayn_agent_run_state", "ayn_agent_states", "ayn_backtests", 
    "ayn_business_news", "ayn_business_timing", "ayn_consensus_predictions", "ayn_consequence_chains", 
    "ayn_consumer_sentiment", "ayn_country_intelligence", "ayn_country_risk_scores", "ayn_crowd_panel", 
    "ayn_daily_run_log", "ayn_dev_agent_memory", "ayn_dev_messages", "ayn_dev_skills", 
    "ayn_early_warnings", "ayn_error_log", "ayn_geopolitical", "ayn_global_predictions", 
    "ayn_gov_policies", "ayn_graph_engine_runs", "ayn_graph_runs", "ayn_health_intel", 
    "ayn_historical_patterns", "ayn_intelligence_accuracy", "ayn_intelligence_lessons", 
    "ayn_job_market", "ayn_kg_edges", "ayn_kg_snapshots", "ayn_lean_context", "ayn_market_prices", 
    "ayn_market_snapshot", "ayn_master_predictions", "ayn_mind", "ayn_opportunity_alerts", 
    "ayn_platform_states", "ayn_prediction_accuracy", "ayn_prediction_cluster_members", 
    "ayn_prediction_clusters", "ayn_prediction_domains", "ayn_prediction_graph_edges", 
    "ayn_prediction_ledger", "ayn_prediction_lessons", "ayn_prediction_outcomes", "ayn_prediction_performance", 
    "ayn_prediction_rules", "ayn_prediction_votes", "ayn_predictions", "ayn_private_simulations", 
    "ayn_real_estate", "ayn_resolution_queue", "ayn_sales_pipeline", "ayn_scenarios", "ayn_sector_intel", 
    "ayn_simulation_reports", "ayn_snapshot_history", "ayn_social_interactions", "ayn_startup_intel", 
    "ayn_supply_chain", "ayn_tech_disruption", "ayn_trade_flows", "ayn_truth_log", "ayn_wisdom_frameworks", 
    "ayn_world_actors", "ayn_world_events", "ayn_world_predictions", "ayn_world_signals", 
    "ayn_world_simulations", "beta_feedback", "brain_insights", "brain_logs", "building_codes", 
    "calculation_history", "chart_analyses", "chat_sessions", "climate_zones", "company_journal", 
    "company_objectives", "company_state", "competitor_tweets", "compliance_inputs", 
    "compliance_projects", "compliance_results", "contact_messages", "creator_profiles", "credit_gifts", 
    "custom_orders", "device_fingerprints", "drawing_projects", "email_logs", "emergency_alerts", 
    "employee_discussions", "employee_reflections", "employee_states", "employee_tasks", 
    "engineering_activity", "engineering_portfolio", "engineering_projects", "error_group_resolutions", 
    "error_logs", "faq_items", "favorite_chats", "founder_context", "founder_directives", 
    "grading_projects", "inbound_email_replies", "ip_blocks", "llm_cost_daily", "llm_failures", 
    "llm_models", "llm_usage_logs", "marketing_competitors", "material_prices", "message_ratings", 
    "messages", "nda_agreements", "news_cache", "password_reset_tokens", "payment_events", 
    "pending_pin_changes", "performance_metrics", "pinned_chats", "profiles", "rate_limits", 
    "saved_insights", "saved_responses", "security_audit_logs", "security_incidents", "security_logs", 
    "service_applications", "service_economics", "stress_test_metrics", "subscription_plans", 
    "support_ticket_replies", "support_tickets", "system_config", "system_health_checks", "system_logs", 
    "system_reports", "system_status", "terms_consent_log", "test_results", "test_runs", 
    "threat_detection", "ticket_messages", "twitter_posts", "usage_logs", "user_ai_limits", 
    "user_memory", "user_preferences", "user_roles", "user_sessions", "user_settings", 
    "user_subscriptions", "user_usage_daily", "users", "visitor_analytics"
];

const actual = [
    "_migrations", "access_grants", "admin_notification_config", "admin_notification_log", 
    "agent_event_debounce", "agent_telegram_bots", "ai_mode_configs", "alert_history", 
    "api_rate_limits", "app_settings", "application_replies", "ayn_accuracy_calibration", 
    "ayn_activity_log", "ayn_agent_coalitions", "ayn_agent_memory", "ayn_agent_memory_log", 
    "ayn_agent_messages", "ayn_agent_opinion_shifts", "ayn_agent_relationships", "ayn_agent_run_state", 
    "ayn_agent_states", "ayn_backtests", "ayn_business_news", "ayn_business_timing", 
    "ayn_consensus_predictions", "ayn_consequence_chains", "ayn_consumer_sentiment", 
    "ayn_country_intelligence", "ayn_country_risk_scores", "ayn_crowd_panel", "ayn_daily_run_log", 
    "ayn_dev_agent_memory", "ayn_dev_messages", "ayn_dev_skills", "ayn_early_warnings", 
    "ayn_error_log", "ayn_geopolitical", "ayn_global_predictions", "ayn_gov_policies", 
    "ayn_graph_engine_runs", "ayn_graph_runs", "ayn_health_intel", "ayn_historical_patterns", 
    "ayn_intelligence_accuracy", "ayn_intelligence_lessons", "ayn_job_market", "ayn_kg_edges", 
    "ayn_kg_snapshots", "ayn_lean_context", "ayn_market_prices", "ayn_market_snapshot", 
    "ayn_master_predictions", "ayn_mind", "ayn_opportunity_alerts", "ayn_platform_states", 
    "ayn_prediction_accuracy", "ayn_prediction_cluster_members", "ayn_prediction_clusters", 
    "ayn_prediction_domains", "ayn_prediction_graph_edges", "ayn_prediction_ledger", 
    "ayn_prediction_lessons", "ayn_prediction_outcomes", "ayn_prediction_performance", 
    "ayn_prediction_rules", "ayn_prediction_votes", "ayn_predictions", "ayn_private_simulations", 
    "ayn_real_estate", "ayn_resolution_queue", "ayn_sales_pipeline", "ayn_scenarios", 
    "ayn_sector_intel", "ayn_simulation_reports", "ayn_snapshot_history", "ayn_social_interactions", 
    "ayn_startup_intel", "ayn_supply_chain", "ayn_tech_disruption", "ayn_trade_flows", 
    "ayn_truth_log", "ayn_wisdom_frameworks", "ayn_world_actors", "ayn_world_events", 
    "ayn_world_predictions", "ayn_world_signals", "ayn_world_simulations", "beta_feedback", 
    "brain_insights", "brain_logs", "building_codes", "calculation_history", "chart_analyses", 
    "chat_sessions", "climate_zones", "company_journal", "company_objectives", "company_state", 
    "competitor_tweets", "compliance_inputs", "compliance_projects", "compliance_results", 
    "contact_messages", "creator_profiles", "credit_gifts", "custom_orders", "device_fingerprints", 
    "drawing_projects", "email_logs", "emergency_alerts", "employee_discussions", 
    "employee_reflections", "employee_states", "employee_tasks", "engineering_activity", 
    "engineering_portfolio", "engineering_projects", "error_group_resolutions", "error_logs", 
    "faq_items", "favorite_chats", "founder_context", "founder_directives", "inbound_email_replies", 
    "ip_blocks", "llm_cost_daily", "llm_failures", "llm_models", "llm_usage_logs", 
    "marketing_competitors", "material_prices", "message_ratings", "messages", "nda_agreements", 
    "news_cache", "password_reset_tokens", "payment_events", "pending_pin_changes", 
    "performance_metrics", "pg_stat_statements", "pg_stat_statements_info", "pinned_chats", 
    "profiles", "rate_limits", "saved_insights", "saved_responses", "security_audit_logs", 
    "security_incidents", "security_logs", "service_applications", "service_economics", 
    "stress_test_metrics", "support_ticket_replies", "support_tickets", "system_config", 
    "system_health_checks", "system_logs", "system_reports", "system_status", "terms_consent_log", 
    "test_results", "test_runs", "threat_detection", "ticket_messages", "twitter_posts", 
    "usage_logs", "user_ai_limits", "user_memory", "user_preferences", "user_roles", 
    "user_sessions", "user_settings", "user_subscriptions", "user_usage_daily", "users", 
    "visitor_analytics"
];

const missing = expected.filter(t => !actual.includes(t));
const extra = actual.filter(t => !expected.includes(t));

console.log("MISSING_TABLES:");
console.log(missing);
console.log("EXTRA_TABLES:");
console.log(extra);
