import { createClient } from "npm:@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

function generateRefNumber(): string {
  const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
  let ref = "AYN-";
  for (let i = 0; i < 8; i++) ref += chars[Math.floor(Math.random() * chars.length)];
  return ref;
}

function formatDate(): string {
  return new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
}

const brainSvg = `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="#111" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5a3 3 0 1 0-5.997.125 4 4 0 0 0-2.526 5.77 4 4 0 0 0 .556 6.588A4 4 0 1 0 12 18Z"/><path d="M12 5a3 3 0 1 1 5.997.125 4 4 0 0 1 2.526 5.77 4 4 0 0 1-.556 6.588A4 4 0 1 1 12 18Z"/><path d="M15 13a4.5 4.5 0 0 1-3-4 4.5 4.5 0 0 1-3 4"/><path d="M17.599 6.5a3 3 0 0 0 .399-1.375"/><path d="M6.003 5.125A3 3 0 0 0 6.401 6.5"/><path d="M3.477 10.896a4 4 0 0 1 .585-.396"/><path d="M19.938 10.5a4 4 0 0 1 .585.396"/><path d="M6 18a4 4 0 0 1-1.967-.516"/><path d="M19.967 17.484A4 4 0 0 1 18 18"/></svg>`;

function buildHTML(title: string, sections: Array<{ heading: string; content: string; bullets?: string[] }>, docType: string, refNumber: string): string {
  const sectionsHTML = sections.map((s, i) => {
    const bulletHTML = s.bullets?.length
      ? `<ul style="margin:8px 0 0 24px;color:#374151;line-height:1.8">${s.bullets.map(b => `<li style="margin-bottom:4px">${b}</li>`).join("")}</ul>`
      : "";
    return `
      <div style="margin-bottom:28px;break-inside:avoid">
        <h2 style="font-size:16px;font-weight:700;color:#1e293b;margin:0 0 10px;border-bottom:1px solid #e5e7eb;padding-bottom:6px">${i + 1}. ${s.heading}</h2>
        <p style="font-size:14px;color:#374151;line-height:1.8;margin:0;white-space:pre-line">${s.content}</p>
        ${bulletHTML}
      </div>`;
  }).join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>${title}</title>
<style>
  @page { size: A4; margin: 20mm 18mm; }
  @media print {
    body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    .no-print { display: none !important; }
  }
  * { box-sizing: border-box; }
  body { font-family: 'Segoe UI', 'Helvetica Neue', Arial, sans-serif; margin: 0; padding: 0; background: #fff; color: #1e293b; }
  .page { max-width: 800px; margin: 0 auto; padding: 40px 48px; }
</style>
</head>
<body>
<div class="page">
  <!-- Header -->
  <div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:8px">
    <div style="display:flex;align-items:center;gap:10px">
      ${brainSvg}
      <span style="font-size:42px;font-weight:800;letter-spacing:-2px;color:#111">AYN</span>
    </div>
    <div style="text-align:right;font-size:11px;color:#6b7280;line-height:1.6">
      <div>Report: <strong>${refNumber}</strong></div>
      <div>Date: ${formatDate()}</div>
      <div>Type: ${docType}</div>
    </div>
  </div>

  <!-- Blue Divider -->
  <div style="height:3px;background:#2563eb;border-radius:2px;margin:0 0 32px"></div>

  <!-- Title -->
  <h1 style="font-size:24px;font-weight:800;color:#0f172a;margin:0 0 8px;text-decoration:underline;text-underline-offset:6px;text-decoration-color:#2563eb">${title}</h1>
  <p style="font-size:12px;color:#6b7280;margin:0 0 32px">Generated by AYN Intelligence · ${formatDate()}</p>

  <!-- Sections -->
  ${sectionsHTML}

  <!-- Footer -->
  <div style="margin-top:48px;padding-top:16px;border-top:2px solid #e5e7eb;text-align:center">
    <p style="font-size:11px;color:#9ca3af;margin:0">AYN · Intelligent Business Solutions</p>
    <p style="font-size:10px;color:#d1d5db;margin:4px 0 0">This document is confidential and generated by AI. Ref: ${refNumber}</p>
  </div>
</div>

<!-- Print Button -->
<div class="no-print" style="position:fixed;bottom:24px;right:24px;z-index:100">
  <button onclick="window.print()" style="background:#2563eb;color:#fff;border:none;padding:12px 28px;border-radius:8px;font-size:14px;font-weight:600;cursor:pointer;box-shadow:0 4px 12px rgba(37,99,235,0.3)">
    Save as PDF
  </button>
</div>
</body>
</html>`;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { prompt, documentType = "Business Plan" } = await req.json();
    if (!prompt) return new Response(JSON.stringify({ error: "Prompt is required" }), { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } });

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) throw new Error("LOVABLE_API_KEY not configured");

    const systemPrompt = `You are AYN, a professional business document writer. Generate a structured ${documentType} based on the user's description. Return well-organized sections with clear headings and detailed content. Write professionally and formally. Each section should have substantial content (2-4 paragraphs minimum). Include actionable insights and specific details where possible.`;

    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: { Authorization: `Bearer ${LOVABLE_API_KEY}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: `Create a ${documentType} for: ${prompt}` },
        ],
        tools: [{
          type: "function",
          function: {
            name: "create_document",
            description: "Create a structured business document with title and sections",
            parameters: {
              type: "object",
              properties: {
                title: { type: "string", description: "Document title" },
                sections: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      heading: { type: "string" },
                      content: { type: "string", description: "Main paragraph content for this section" },
                      bullets: { type: "array", items: { type: "string" }, description: "Optional bullet points" },
                    },
                    required: ["heading", "content"],
                  },
                },
              },
              required: ["title", "sections"],
            },
          },
        }],
        tool_choice: { type: "function", function: { name: "create_document" } },
      }),
    });

    if (!response.ok) {
      const errText = await response.text();
      console.error("AI gateway error:", response.status, errText);
      if (response.status === 429) return new Response(JSON.stringify({ error: "Rate limited. Please try again shortly." }), { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } });
      if (response.status === 402) return new Response(JSON.stringify({ error: "AI credits exhausted. Please top up." }), { status: 402, headers: { ...corsHeaders, "Content-Type": "application/json" } });
      throw new Error(`AI error: ${response.status}`);
    }

    const data = await response.json();
    const toolCall = data.choices?.[0]?.message?.tool_calls?.[0];
    if (!toolCall) throw new Error("AI did not return structured data");

    const args = JSON.parse(toolCall.function.arguments);
    const refNumber = generateRefNumber();
    const html = buildHTML(args.title, args.sections, documentType, refNumber);

    return new Response(JSON.stringify({ html, title: args.title, refNumber }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error("generate-business-document error:", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
