// This file was originally scaffolded by the Lovable platform's own
// generator (hence the header below); this app is now fully self-hosted
// and nothing in its real build (npm install && npm run build, per
// auto_deploy.sh) regenerates this file, so editing it directly is safe.
//
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

import { SUPABASE_URL, SUPABASE_ANON_KEY } from '@/config';

// The checked-in generated schema predates these migrations. Keep the client
// typed without weakening it to `any` until it can be regenerated from the
// user-managed database. Each addition below mirrors the migration's fields.
type PublicSchema = Database['public'];
type Tables = PublicSchema['Tables'];
type Functions = PublicSchema['Functions'];
type ExtendTable<T, R, I, U> = Omit<T, 'Row' | 'Insert' | 'Update'> & {
  Row: T extends { Row: infer V } ? V & R : R;
  Insert: T extends { Insert: infer V } ? V & I : I;
  Update: T extends { Update: infer V } ? V & U : U;
};
type PostingExtras = {
  category: string | null; city: string | null; closure_status: string | null;
  salary_text_min: number | null; salary_text_max: number | null; salary_text_currency: string | null; salary_text_period: string | null; work_mode_text: string | null; benefits: string[] | null;
  first_seen_at: string | null; last_seen_at: string | null; repost_count: number | null; years_required: number | null; sponsorship: string | null;
  employment_type: string | null; mass_posting_count: number | null;
  salary_currency: string | null; salary_max: number | null; salary_min: number | null;
  scam_reason: string | null; scam_suspected: boolean | null;
  seniority: string | null; skills: string[] | null; work_mode: string | null;
};
type JobExtras = { application_status: string; application_status_changed_at: string };
type VersionExtras = { match_pct: number | null; still_missing: Database['public']['Tables']['resumes']['Row']['content'] };
type Seen = {
  Row: { user_id: string; job_posting_id: string; seen_at: string };
  Insert: { user_id: string; job_posting_id: string; seen_at?: string };
  Update: { user_id?: string; job_posting_id?: string; seen_at?: string };
  Relationships: [];
};
type SkillToLearn = {
  Row: { id: string; user_id: string; job_id: string | null; job_title: string | null; company: string | null; skill: string; added_at: string; learned_at: string | null };
  Insert: { id?: string; user_id: string; job_id?: string | null; job_title?: string | null; company?: string | null; skill: string; added_at?: string; learned_at?: string | null };
  Update: { id?: string; user_id?: string; job_id?: string | null; job_title?: string | null; company?: string | null; skill?: string; added_at?: string; learned_at?: string | null };
  Relationships: [];
};
type InboxMessage = {
  Row: { id: string; reveal_request_id: string; sender_role: string; sender_user_id: string | null; kind: string; body: string | null; call_url: string | null; call_scheduled_at: string | null; status: string; block_reason: string | null; read_at: string | null; created_at: string };
  Insert: { id?: string; reveal_request_id: string; sender_role: string; sender_user_id?: string | null; kind?: string; body?: string | null; call_url?: string | null; call_scheduled_at?: string | null; status?: string; block_reason?: string | null; read_at?: string | null; created_at?: string };
  Update: { id?: string; reveal_request_id?: string; sender_role?: string; sender_user_id?: string | null; kind?: string; body?: string | null; call_url?: string | null; call_scheduled_at?: string | null; status?: string; block_reason?: string | null; read_at?: string | null; created_at?: string };
  Relationships: [];
};
type CurrentDatabase = Omit<Database, 'public'> & {
  public: Omit<PublicSchema, 'Tables' | 'Functions'> & {
    Tables: Omit<Tables, 'job_postings' | 'jobs' | 'resume_versions'> & {
      job_postings: ExtendTable<Tables['job_postings'], PostingExtras, Partial<PostingExtras>, Partial<PostingExtras>>;
      jobs: ExtendTable<Tables['jobs'], JobExtras, Partial<JobExtras>, Partial<JobExtras>>;
      resume_versions: ExtendTable<Tables['resume_versions'], VersionExtras, Partial<VersionExtras>, Partial<VersionExtras>>;
      job_postings_seen: Seen;
      skills_to_learn: SkillToLearn;
      inbox_messages: InboxMessage;
    };
    Functions: Functions & {
      company_hiring_status: { Args: { p_company_slug: string }; Returns: string | null };
      company_hiring_status_batch: { Args: { p_company_slugs: string[] }; Returns: { company_slug: string; status: string | null }[] };
      save_primary_resume: { Args: { p_id: string; p_title: string; p_content: Database['public']['Tables']['resumes']['Row']['content']; p_ats_score: number | null; p_ats_issues: Database['public']['Tables']['resumes']['Row']['content'] | null }; Returns: string };
      job_market_snapshot: { Args: never; Returns: Database['public']['Tables']['resumes']['Row']['content'] };
    };
  };
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// v3.313.0 — real, reported bug: leaving AYN idle/backgrounded for a
// while, then coming back and clicking Profile or another account page,
// showed a raw JWT error and blank content. Root-caused, not guessed at:
// browsers throttle a background tab's own timers, so supabase-js's
// AUTO-REFRESH ticker (which normally renews the access token before it
// expires) can fall behind. The SDK does correctly restart that ticker
// the moment the tab becomes visible again (its own
// _onVisibilityChanged handler, confirmed directly in the installed
// package's source) — but that refresh runs ASYNCHRONOUSLY, and there is
// a real, unavoidable race: a request fired the instant the tab refocuses
// can still go out with the stale token before the refresh finishes,
// getting a genuine 401 back from the server. Confirmed live against the
// real deployed backend with a real expired JWT: PostgREST answers
// {"code":"PGRST301",...}, the resume-hub edge function answers
// {"error":"Invalid session"} — both 401, both real, neither retried by
// anything in this app before now.
//
// Fixed once, here, for every caller at once — every `.from()` query and
// every fetch through resumeHub.ts's own call() all route through this
// one client, so intercepting at the fetch layer covers the whole app
// rather than patching each page's own load function separately. On a
// 401 that actually looks like an expired/invalid JWT (checked
// narrowly, never a real 403 like account_suspended/account_restricted,
// which this can't touch since those aren't 401 at all), it refreshes
// the session once and re-issues the exact same request with the fresh
// token — silently recovering from the race instead of surfacing it.
// If the refresh itself fails (a genuinely dead session, not just a
// stale token), the original 401 is returned unchanged, so a real
// "please sign in again" case still surfaces normally rather than
// silently retrying forever.
let clientRef: ReturnType<typeof createClient<CurrentDatabase>> | null = null;

async function fetchWithAuthRetry(input: RequestInfo | URL, init?: RequestInit): Promise<Response> {
  const res = await fetch(input, init);
  if (res.status !== 401 || !clientRef) return res;

  let looksLikeExpiredJwt = false;
  try {
    const body = await res.clone().json();
    const msg = String(body?.message || body?.error || '');
    looksLikeExpiredJwt = body?.code === 'PGRST301' || /jwt|invalid session|invalid token/i.test(msg);
  } catch {
    // Not JSON, or no body -- not the shape either real failure path above
    // actually produces, so leave the original response alone.
  }
  if (!looksLikeExpiredJwt) return res;

  const { data, error } = await clientRef.auth.refreshSession();
  if (error || !data.session) return res; // a genuinely dead session -- surface the real 401, don't loop

  const headers = new Headers(init?.headers);
  headers.set('Authorization', `Bearer ${data.session.access_token}`);
  return fetch(input, { ...init, headers });
}

export const supabase = createClient<CurrentDatabase>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
  global: {
    headers: {
      'x-application-name': 'ayn-web',
    },
    fetch: fetchWithAuthRetry,
  },
  db: {
    schema: 'public',
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});
clientRef = supabase;
