// This file was originally scaffolded by the Lovable platform's own
// generator (hence the header below); this app is now fully self-hosted
// and nothing in its real build (npm install && npm run build, per
// auto_deploy.sh) regenerates this file, so editing it directly is safe.
//
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

import { SUPABASE_URL, SUPABASE_ANON_KEY } from '@/config';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// v3.313.0 — real, reported bug: leaving AYN idle/backgrounded for a
// while, then coming back and clicking Profile or another account page,
// showed a raw JWT error and blank content. Root-caused, not guessed at:
// browsers throttle a background tab's own timers, so supabase-js's
// AUTO-REFRESH ticker (which normally renews the access token before it
// expires) can fall behind. The SDK does correctly restart that ticker
// the moment the tab becomes visible again (its own
// _onVisibilityChanged handler, confirmed directly in the installed
// package's source) — but that refresh runs ASYNCHRONOUSLY, and there is
// a real, unavoidable race: a request fired the instant the tab refocuses
// can still go out with the stale token before the refresh finishes,
// getting a genuine 401 back from the server. Confirmed live against the
// real deployed backend with a real expired JWT: PostgREST answers
// {"code":"PGRST301",...}, the resume-hub edge function answers
// {"error":"Invalid session"} — both 401, both real, neither retried by
// anything in this app before now.
//
// Fixed once, here, for every caller at once — every `.from()` query and
// every fetch through resumeHub.ts's own call() all route through this
// one client, so intercepting at the fetch layer covers the whole app
// rather than patching each page's own load function separately. On a
// 401 that actually looks like an expired/invalid JWT (checked
// narrowly, never a real 403 like account_suspended/account_restricted,
// which this can't touch since those aren't 401 at all), it refreshes
// the session once and re-issues the exact same request with the fresh
// token — silently recovering from the race instead of surfacing it.
// If the refresh itself fails (a genuinely dead session, not just a
// stale token), the original 401 is returned unchanged, so a real
// "please sign in again" case still surfaces normally rather than
// silently retrying forever.
let clientRef: ReturnType<typeof createClient<Database>> | null = null;

async function fetchWithAuthRetry(input: RequestInfo | URL, init?: RequestInit): Promise<Response> {
  const res = await fetch(input, init);
  if (res.status !== 401 || !clientRef) return res;

  let looksLikeExpiredJwt = false;
  try {
    const body = await res.clone().json();
    const msg = String(body?.message || body?.error || '');
    looksLikeExpiredJwt = body?.code === 'PGRST301' || /jwt|invalid session|invalid token/i.test(msg);
  } catch {
    // Not JSON, or no body -- not the shape either real failure path above
    // actually produces, so leave the original response alone.
  }
  if (!looksLikeExpiredJwt) return res;

  const { data, error } = await clientRef.auth.refreshSession();
  if (error || !data.session) return res; // a genuinely dead session -- surface the real 401, don't loop

  const headers = new Headers(init?.headers);
  headers.set('Authorization', `Bearer ${data.session.access_token}`);
  return fetch(input, { ...init, headers });
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
  global: {
    headers: {
      'x-application-name': 'ayn-web',
    },
    fetch: fetchWithAuthRetry,
  },
  db: {
    schema: 'public',
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});
clientRef = supabase;
